#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift

VIM_DIR="$HOME/.vim"
VIM_CONFIG="$HOME/.vimrc"

NVIM_DIR="$HOME/.config/nvim"
NVIM_CONFIG="$NVIM_DIR/init.vim"

mkdir -p "$VIM_DIR"
mkdir -p "$(dirname "$NVIM_DIR")"

cat "$current_plugin_dir"/index.vim | sed "s~__HABITAT_DOTFILES__~'$dotfiles_dir'~g" > $VIM_CONFIG

ln -snf "$VIM_DIR" "$NVIM_DIR"
ln -snf "$VIM_CONFIG" "$NVIM_CONFIG"

echo "(vim +PlugClean +PlugInstall +PlugUpdate +PlugUpgrade +qall 2>/dev/null 1>/dev/null &)"
if type -t nvim 2>&1 >/dev/null; then
	echo "(nvim +PlugClean +PlugInstall +PlugUpdate +PlugUpgrade +qall 2>/dev/null 1>/dev/null &)"
fi
