#!/usr/bin/env bash
#==============================================================
# => Bash History
#
# Make bash history more inuitive, and overall easier to use
#==============================================================

cat <<\EOF

# I Want my history to last forever and sync wether or not I log out
# http://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows
export HISTFILESIZE=1000000000
export HISTSIZE=$HISTFILESIZE
export HISTCONTROL=ignoredups:erasedups

# append history entries right away
shopt -s histappend
export HISTTIMEFORMAT="%m/%d/%y %T " # Save history timestamps

hist_cmd=""
# append currently un-appended line to file (aka last line that was entered)
hist_cmd+="history -a;"

# clear our list of entered lines
# hist_cmd+="history -c;"

# reload history file
# hist_cmd+="history -r;"

if [ -z "$(echo "$PROMPT_COMMAND" | grep "$hist_cmd")" ]; then
	# add hist_cmd
  export PROMPT_COMMAND="$hist_cmd $PROMPT_COMMAND"
fi
unset hist_cmd

alias histr="history -c; history -r;"
EOF
