#!/usr/bin/env bash

cat <<\EOF
export NVM_DIR="$HOME/.nvm"

if [ ! -s "$NVM_DIR/nvm.sh" ]; then
	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
fi

# this is to get around loading nvm every shell load
# which causes half a second of latency for every terminal
nvm() {
	unset -f nvm

	[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
	nvm "$@"
}

NVM_DEFAULT_ALIAS="$NVM_DIR/alias/default"

if [ -z "$NVM_DEFAULT_ALIAS" ]; then
	echo "Please use 'nvm alias default <version>' so we can set that up for you!" 2>&1
else
	NVM_DEFAULT="$(cat "$NVM_DEFAULT_ALIAS")"
	NVM_DEFAULT_PATH="$NVM_DIR/versions/node/$NVM_DEFAULT/bin/"

	if [ ! -d "$NVM_DEFAULT_PATH" ]; then
		nvm install "$NVM_DEFAULT"
	fi

	if [ -z "$(echo "$PATH" | grep "$NVM_DEFAULT_PATH")" ]; then
		PATH="$NVM_DEFAULT_PATH:$PATH"
	fi
	unset NVM_DEFAULT
	unset NVM_DEFAULT_PATH
fi

unset NVM_DEFAULT_ALIAS
EOF
