#!/usr/bin/env bash

NVM_DIR="$HOME/.nvm"

if [ ! -d "$NVM_DIR" ]; then
	read -rp "Install nvm (y/n)?" choice
	case "$choice" in
		y|Y) echo "Installing";;
		n|N) echo "Bye Bye" && return ;;
		*) echo "invalid" ;;
	esac

	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
fi

if [ -d "$NVM_DIR" ]; then
	echo "export NVM_DIR=$NVM_DIR"
	cat "$NVM_DIR/nvm.sh"
fi
