#!/usr/bin/env bash

NVM_DIR="$HOME/.nvm"

if [ ! -d "$NVM_DIR" ]; then
	read -rp "Install nvm (y/n)?" choice
	case "$choice" in
		y|Y) echo "Installing";;
		n|N) echo "Bye Bye" && return ;;
		*) echo "invalid" ;;
	esac
fi

(curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash 2>/dev/null 1>/dev/null &)

if [ -d "$NVM_DIR" ]; then
	echo "export NVM_DIR='$NVM_DIR'"
  echo ". '$NVM_DIR/nvm.sh' --no-use"
	. "$NVM_DIR"/nvm.sh --no-use
	echo "path_add '$(dirname "$(nvm which default)")' 1"
else
	echo "echo 'nvm failed to install"
fi
