#!/usr/bin/env bash

# URL Tools
# Adds handy command line aliases useful for dealing with URLs
#
# inspired by
# * http://ruslanspivak.com/2010/06/02/urlencode-and-urldecode-from-a-command-line/
# * https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/urltools/urltools.plugin.zsh

exec 2>&1

if type -t node >/dev/null; then
  cat <<\EOF
    alias urlencode='node -e "console.log(encodeURIComponent(process.argv[1]))"'
    alias urldecode='node -e "console.log(decodeURIComponent(process.argv[1]))"'
EOF
elif type -t python3 >/dev/null; then
  cat <<\EOF
    alias urlencode='python3 -c "import sys, urllib.parse as up; print(up.quote_plus(sys.argv[1]))"'
    alias urldecode='python3 -c "import sys, urllib.parse as up; print(up.unquote_plus(sys.argv[1]))"'
EOF
elif type -t python2 >/dev/null; then
  cat <<\EOF
    alias urlencode='python2 -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
    alias urldecode='python2 -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
EOF
elif type -t xxd >/dev/null; then
  cat <<\EOF
    urlencode() {
      echo $@ | tr -d "\n" | xxd -plain | sed "s/\(..\)/%\1/g"
    }
    urldecode() {
      printf $(echo -n $@ | sed 's/\\/\\\\/g;s/\(%\)\([0-9a-fA-F][0-9a-fA-F]\)/\\x\2/g')"\n"
    }
EOF
elif type -t ruby >/dev/null; then
  cat <<\EOF
    alias urlencode='ruby -r cgi -e "puts CGI.escape(ARGV[0])"'
    alias urldecode='ruby -r cgi -e "puts CGI.unescape(ARGV[0])"'
EOF
elif type -t php >/dev/null; then
  cat <<\EOF
    alias urlencode='php -r "echo rawurlencode(\$argv[1]); echo \"\n\";"'
    alias urldecode='php -r "echo rawurldecode(\$argv[1]); echo \"\\n\";"'
EOF
elif type -t perl >/dev/null; then
  if perl -MURI::Encode -e >/dev/null; then
    cat <<\EOF
      alias urlencode='perl -MURI::Encode -ep "uri_encode($ARGV[0]);"'
      alias urldecode='perl -MURI::Encode -ep "uri_decode($ARGV[0]);"'
EOF
  elif perl -MURI::Escape -e >/dev/null; then
    cat <<\EOF
      alias urlencode='perl -MURI::Escape -ep "uri_escape($ARGV[0]);"'
      alias urldecode='perl -MURI::Escape -ep "uri_unescape($ARGV[0]);"'
EOF
  else
    cat <<\EOF
      alias urlencode="perl -e '\$new=\$ARGV[0]; \$new =~ s/([^A-Za-z0-9])/sprintf(\"%%%02X\", ord(\$1))/seg; print \"\$new\n\";'"
      alias urldecode="perl -e '\$new=\$ARGV[0]; \$new =~ s/\%([A-Fa-f0-9]{2})/pack(\"C\", hex(\$1))/seg; print \"\$new\n\";'"
EOF
  fi
fi
