#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift
if [ ! -d "$dotfiles_dir" ]; then
	exit 1
fi

cat <<EOF
for target in "$dotfiles_dir"{,*/,*/*/,*/*/*/}*.syml; do
  if echo "\$target" | grep -q '\*\.syml'; then
    continue;
  fi

	link_name="\${target##*/}"
	link_name="\${link_name%.syml}"
	link_name="\$HOME/.\${link_name}"

	ln -snf "\$target" "\$link_name" &>/dev/null
	unset link_name
done

unset target
EOF
