#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift
if [ ! -d "$dotfiles_dir" ]; then
	exit 1
fi

cat <<EOF

for target in "$dotfiles_dir"{,*/,*/*/,*/*/*/}*.syml; do
  [ ! -e "\$target" ] && continue

	link_name="\$HOME/.\$(basename "\${target%.*}")"

	[ "$(readlink "$link_name")" = "$target" ] && continue
	ln -snf "\$target" "\$link_name" </dev/null &>/dev/null &
	disown
done
EOF
