#!/usr/bin/env bash


# Setup fzf
# ---------
echo "path_add '$HOME/.fzf/bin'"
echo "man_path_add '$HOME/.fzf/man'"
echo "[[ $- == *i* ]] && source '$HOME/.fzf/shell/completion.bash' 2>&1 >/dev/null"
echo "source '$HOME/.fzf/shell/key-bindings.bash' 2>&1 >/dev/null"
