#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift
if [ ! -d "$dotfiles_dir" ]; then
	exit 1
fi

cat <<EOF
while read -r file; do
	. "\$file"
done <<< "\$(find -L "$dotfiles_dir" -name '*.shell')"
EOF
