#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift
if [ ! -d "$dotfiles_dir" ]; then
	exit 1
fi

cat <<EOF
for file in "$dotfiles_dir"{,*/,*/*/,*/*/*/}*.shell; do
	[ -f "\$file" ] && . "\$file"
done
EOF
