#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift

bash_completion="/etc/bash_completion"

if type -t brew >/dev/null 2>&1; then
  prefix="$(brew --prefix)"
  bash_completion="$prefix/etc/profile.d/bash_completion.sh"
fi

if [ -f "$bash_completion" ]; then
  echo ". $bash_completion"
fi
