#!/usr/bin/env bash

current_plugin_dir="$1"; shift
dotfiles_dir="$1"; shift

bash_completion="/etc/bash_completion"
bash_completion_two="/share/bash-completion/bash_completion"

# TODO: for some reason running this makes the second line $ dissappear
if type -t npm 2>&1 >/dev/null; then
	echo 'if [ -z "$NPM_COMPLETION_DONE" ]; then'
  npm completion
	echo 'NPM_COMPLETION_DONE=1'
	echo 'fi'
fi

if [ -f "$bash_completion_two" ]; then
  file="$bash_completion_two"
elif type -t brew 2>&1 >/dev/null && [ -f "$(brew --prefix)$bash_completion_two" ]; then
  file="$(brew --prefix)$bash_completion_two"
elif [ -f "$bash_completion" ]; then
  file="$bash_completion"
elif type -t brew 2>&1 >/dev/null && [ -f "$(brew --prefix)$bash_completion" ]; then
  file="$(brew --prefix)$bash_completion"
fi

if [ -n "$file" ]; then
	cat "$file"
fi
