#!/usr/bin/env bash

ASDF_DIR="$HOME/.asdf"
URL="https://github.com/asdf-vm/asdf.git"

if [ ! -d "$ASDF_DIR" ]; then
  (git clone "$URL" "$ASDF_DIR" --branch v0.13.1 && \
    . "$ASDF_DIR/asdf.sh" \
    asdf plugin add nodejs \
    asdf plugin add python \
    2>&1 >/dev/null &)
fi



if [ -d "$ASDF_DIR" ]; then
  echo "ASDF_DIR='$ASDF_DIR'"
  echo '. "$ASDF_DIR/asdf.sh"'
  echo "asdf install 2>&1 >/dev/null &"
  echo "disown"
fi
