bash install-software.sh
bash system-settings.sh

echo "Settings:"
echo "Now change mouse/trackpad settings"
echo "  a. Mouse"
echo "    i. Point & Click: Secondary Click Only + fastest mouse speed"
echo "    ii. More Gestures: All checked"
echo "    iii. Uncheck Scroll direction: Natural"
echo "  b. Trackpad"
echo "    i. Point & Click: All but look up and data detectors"
echo "mouse double click speed 3 notches below max"
echo "Night shift and 1 min Do not Disturb"
echo "Setup touch id"
echo "Show battery percentage in bar"
echo "Add sound icon to menu bar"
echo "Add Path to finder toolbar"
echo "Add Favorites"
echo "Change computer name via System Preferences -> Sharing -> Computer Name: "
echo "System appearnce to dark always"
echo "bottom bar: "
echo "- finder"
echo "- zoom"
echo "- chrome"
echo "- logitech camera"
echo "- system settings"
echo "- spotify"
echo "- speedcrunch"
echo "- devutils"
echo "- activity monitor"
echo "- browserstack local"
echo "- sublime"
echo "- vscodium"
echo "- openvpn"

echo "Open Rectangle and import ./config/RectangleConfig"
echo "Set iterm to use settings from ./config/iterm2 https://stackoverflow.com/questions/22943676/how-to-export-iterm2-profiles"
echo "Use ./config/mac-mouse-fix.plist and https://github.com/noah-nuebling/mac-mouse-fix/discussions/236"
echo "Use ./config/karabiner.json in karabiner"

echo "Install logitune https://support.logi.com/hc/en-nz/articles/360024849133-Download-HD-Pro-Webcam-C920"
echo "Install Epson printer utils"

